version: '3.7'
services:
  mongo:
    ports:
      - '27888:27017'
    image: 'docker.io/mongo:4.2'
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  
  redis:
    image: docker.io/redis
    command: redis-server --requirepass verysecretpwd
    ports:
      - 6379:6379
    volumes:
      - redis:/var/redis

  zookeeper:
    image: docker.io/confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: docker.io/confluentinc/cp-kafka:6.2.1
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1 
  
#MICROSERVIZI
  it-fse-srv-log-ingestion:
    image: it-fse-gtw-runner                                                                                                                                                                           
    build:
      context: ./it-fse-gtw-runner/
    environment:
      URL: ${REPO_BASE_URL}/it-fse-srv-log-ingestion.git
      BRANCH: feature/sprint1
      PORT: 8018
    volumes: 
      - mvn-cache:/root/.m2
    depends_on:
      - kafka
      - mongo
    network_mode: "host"
  
  it-fse-gtw-indexer:
    image: it-fse-gtw-runner
    build:
      context: ./it-fse-gtw-runner/
    environment:
      URL: ${REPO_BASE_URL}/it-fse-gtw-indexer.git
      BRANCH: feature/UAT_200622
      PORT: 8015
    volumes: 
      - mvn-cache:/root/.m2
    depends_on:
      - kafka
      - mongo
    network_mode: "host"
  
  it-fse-gtw-publisher:                                                                                                         
    image: it-fse-gtw-runner
    build:
      context: ./it-fse-gtw-runner/
    environment:
      URL: ${REPO_BASE_URL}/it-fse-gtw-publisher.git
      BRANCH: feature/UAT_200622
      PORT: 8016
    volumes: 
      - mvn-cache:/root/.m2
    depends_on:
      - kafka
      - mongo
    network_mode: "host"

  it-fse-gtw-validator:
    image: it-fse-gtw-runner
    build:
      context: ./it-fse-gtw-runner/
    environment:
      URL: ${REPO_BASE_URL}/it-fse-gtw-validator.git
      BRANCH: feature/UAT_200622
      PORT: 8012
    volumes: 
      - mvn-cache:/root/.m2
    depends_on:
      - kafka
      - mongo
    network_mode: "host"

  it-fse-gtw-dispatcher:
    image: it-fse-gtw-runner
    build:
      context: ./it-fse-gtw-runner/
    environment:
      URL: ${REPO_BASE_URL}/it-fse-gtw-dispatcher.git
      BRANCH: feature/UAT_200622
      PORT: 8010
    volumes: 
      - mvn-cache:/root/.m2
    depends_on:
      - kafka
      - mongo
    network_mode: "host"

  it-fse-gtw-fhir-mapping:
    image: it-fse-gtw-runner
    build:
      context: ./it-fse-gtw-runner/
    environment:
      URL: ${REPO_BASE_URL}/it-fse-gtw-fhir-mapping.git
      BRANCH: feature/UAT_200622
      PORT: 8014
    volumes: 
      - mvn-cache:/root/.m2
    depends_on:
      - kafka
      - mongo
    network_mode: "host"

  it-fse-gtw-status-check:
    image: it-fse-gtw-runner
    build:
      context: ./it-fse-gtw-runner/
    environment:
      URL: ${REPO_BASE_URL}/it-fse-gtw-status-check.git
      BRANCH: feature/UAT_200622
      PORT: 8017
    volumes: 
      - mvn-cache:/root/.m2
    depends_on:
      - kafka
      - mongo
    network_mode: "host"

  it-fse-gtw-rules-manager:
    image: it-fse-gtw-runner
    build:
      context: ./it-fse-gtw-runner/
    environment:
      URL: ${REPO_BASE_URL}/it-fse-gtw-rules-manager.git
      BRANCH: feature/UAT_200622
      PORT: 8011
    volumes: 
      - mvn-cache:/root/.m2
    depends_on:
      - kafka
      - mongo
    network_mode: "host"
 
  it-fse-gtw-status-manager:
    image: it-fse-gtw-runner
    build:
      context: ./it-fse-gtw-runner/
    environment:
      URL: ${REPO_BASE_URL}/it-fse-gtw-status-manager.git
      BRANCH: feature/UAT_200622
      PORT: 8013
    volumes: 
      - mvn-cache:/root/.m2
    depends_on:
      - kafka
      - mongo
    network_mode: "host"
 
volumes:
 mongodb:
 redis:
 mvn-cache:
